import type { Metadata } from "next";
import Navbar from "./components/navbar";
import "./globals.css";
import { GlobalProvider } from "./contexts/globalContexts";

export const metadata: Metadata = {
  title: "ByeBuy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          <Navbar />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
